#extra script for PIO to work with STM32 platform and no framework and source generated by CubeMX
Import("env", "projenv")
env.Append(CPPDEFINES=["USE_HAL_DRIVER"])
env.Append(CCFLAGS=["--specs=nano.specs"])
for i, flag in enumerate(projenv["LINKFLAGS"]):
    if flag == "-nostartfiles":
        env["LINKFLAGS"][i] = "--specs=nosys.specs"
    if flag == "-nostdlib":
        env["LINKFLAGS"][i] = "--specs=nano.specs"